@startuml

component tccore as "Trusted Connector"

component chapi as "clearing-house-api"
component docapi as "document-api"
component keyapi as "keyring-api"

database chmongo as "clearing-house-mongo"
database docmongo as "document-mongo"
database keymongo as "keyring-mongo"

tccore --> chapi
chapi -- chmongo
chapi --> docapi
chapi --> keyapi
docapi -- docmongo
docapi --> keyapi
keyapi -- keymongo

@enduml