database_url: localhost
database_port: 27019
init_db: true

document_api_url: http://localhost:8001
blockchain_api_url: http://172.31.6.49:8003
keyring_api_url: http://localhost:8002
daps_api_url: https://daps.aisec.fraunhofer.de
server_name: https://clearinghouse.aisec.fraunhofer.de/
server_model: 4.0.0
