name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ids-clearing-house-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    # TODO: do not use caching for actual release builds, aka ones that start with v*
    - uses: Swatinem/rust-cache@v1        
    - name: Build clearing-house-api
      run: |
        cd clearing-house-app
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.IDS_CLEARING_HOUSE_CORE_TOKEN }}"
        cargo build --release
    
    - name: Build build image
      run: |
        cd clearing-house-app
        docker build . --file Dockerfile --tag $IMAGE_NAME
    
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/Fraunhofer-AISEC/$IMAGE_NAME

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
      
      
